name = "doom-gloom"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "429fd3d3981ef9aa3a54adbe128c4f9f88b1082eaa752ea50b1679f1df579019"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
