# Project
mod_name=Doom & Gloom
mod_author=Team Galena
mod_id=doom_and_gloom
mod_version=0.0.0-dev
release_type=beta

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Minecraft
minecraft_version=1.20.1

# Forge
forge_version=47.3.0
kotlin_forge_version=4.3.0

# Fabric
fabric_api_version=0.92.6+1.20.1
fabric_loader_version=0.17.3

# Mixin
mixin_version=0.8.5
mixin_extras_version=0.4.1

# Other Dependencies
blueprint_version=7.1.0
jei_version=15.0.0.12

repository=teamgalena/doomandgloom
maven_group=dev.galena
modrinth_project=NdwUq6vV
curseforge_project=1130903