[versions]
multikulti = "1.21.1-1.2.4"
jei = "19.27.0.340"
moonlight = "1.21-2.29.20"
pathfinding-debug = "1.21.1-1.1.0"
galena-hats = "1.21.1-1.2.5"

[libraries]
multikulti-core = { group = "com.possible-triangle", name = "multikulti-core-neoforge", version.ref = "multikulti" }
multikulti-datagen = { group = "com.possible-triangle", name = "multikulti-datagen-neoforge", version.ref = "multikulti" }

galena-hats-neoforge = { "group" = "dev.galena", name = "hats-neoforge", version.ref = "galena-hats" }
galena-hats-fabric = { "group" = "dev.galena", name = "hats-fabric", version.ref = "galena-hats" }

oreganized = { "group" = "dev.galena", name = "oreganized", version = "5.1.2" }

dye-depot-neoforge = { group = "com.ninni.dye_depot", name = "dye_depot", version = "1.21.1-2.0.2-neoforge" }
dye-depot-fabric = { group = "com.ninni.dye_depot", name = "dye_depot", version = "1.21.1-2.0.2-fabric" }

jei-neoforge = { group = "mezz.jei", name = "jei-1.21.1-neoforge", version.ref = "jei" }
jei-fabric = { group = "mezz.jei", name = "jei-1.21.1-fabric", version.ref = "jei" }

moonlight-lib-common = { group = "net.mehvahdjukaar", name = "moonlight", version.ref = "moonlight" }
moonlight-lib-neoforge = { group = "net.mehvahdjukaar", name = "moonlight-neoforge", version.ref = "moonlight" }
moonlight-lib-fabric = { group = "net.mehvahdjukaar", name = "moonlight-fabric", version.ref = "moonlight" }

farmers-delight-fabric = { group = "vectorwing", name = "FarmersDelight", version = "1.20.1-2.4.1+refabricated" }

pathfinding-debug-neoforge = { group = "com.possible-triangle", name = "pathfinding_renderer-neoforge", version.ref = "pathfinding-debug" }
pathfinding-debug-fabric = { group = "com.possible-triangle", name = "pathfinding_renderer-fabric", version.ref = "pathfinding-debug" }
