[versions]
multikulti = "1.20.1-45-SNAPSHOT"
jei = "15.20.0.106"
moonlight = "1.20-2.16.15"
pathfinding-debug = "1.20.1-1.1.0"

[libraries]
multikulti-core = { group = "com.possible-triangle", name = "multikulti-core-forge", version.ref = "multikulti" }
multikulti-datagen = { group = "com.possible-triangle", name = "multikulti-datagen-forge", version.ref = "multikulti" }
multikulti-datagen-fix = { group = "com.possible-triangle", name = "multikulti-datagen-forge-fix", version.ref = "multikulti" }

galena-hats = { "group" = "dev.galena", name = "hats-forge", version = "1.20.1-1.2.2" }
oreganized = { "group" = "dev.galena", name = "oreganized", version = "4.3.1" }
blueprint = { group = "com.teamabnormals", name = "blueprint", version = "1.20.1-7.1.0" }

dye-depot = { group = "com.ninni.dye_depot", name = "dye_depot", version = "1.20.1-1.2.2-forge" }

jei-forge = { group = "mezz.jei", name = "jei-1.20.1-forge", version.ref = "jei" }
jei-fabric = { group = "mezz.jei", name = "jei-1.20.1-fabric", version.ref = "jei" }

moonlight-lib-common = { group = "net.mehvahdjukaar", name = "moonlight", version.ref = "moonlight" }
moonlight-lib-forge = { group = "net.mehvahdjukaar", name = "moonlight-forge", version.ref = "moonlight" }
moonlight-lib-fabric = { group = "net.mehvahdjukaar", name = "moonlight-fabric", version.ref = "moonlight" }

pathfinding-debug-forge = { group = "com.possible-triangle", name = "pathfinding_renderer-forge", version.ref = "pathfinding-debug" }
pathfinding-debug-fabric = { group = "com.possible-triangle", name = "pathfinding_renderer-fabric", version.ref = "pathfinding-debug" }

[plugins]
parchment = { id = "org.parchmentmc.librarian.forgegradle", version = "1.+" }
