name = "doom-gloom"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80e1bbd60ae1a01ca8ca60517b1126b33f763cef7e85320a063c53ab06aa74cb"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
