name = "doom-gloom"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b87aaa5532a42f1b41559b5b36c73f7e20bae1734164dcbd3e67959d6fd8e25"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
